<!-- Autocomplete
<h2 class="demoHeaders">자동완성</h2>
<div>
	<input id="autocomplete" title="type &quot;a&quot;">
</div>
 -->




<!-- Dialog NOTE: Dialog is not generated by UI in this demo so it can be visually styled in themeroller
<h2 class="demoHeaders">Dialog</h2>
<p><a href="#" id="dialog-link" class="ui-state-default ui-corner-all"><span class="ui-icon ui-icon-newwin"></span>다이얼로그 열기</a></p>

<h2 class="demoHeaders">Overlay and Shadow Classes <em>(not currently used in UI widgets)</em></h2>
<div style="position: relative; width: 96%; height: 200px; padding:1% 2%; overflow:hidden;" class="fakewindowcontain">
	<p>내용물 1</p>
-->
	<!-- ui-dialog 
<div class="ui-overlay"><div class="ui-widget-overlay"></div><div class="ui-widget-shadow ui-corner-all" style="width: 302px; height: 152px; position: absolute; left: 50px; top: 30px;"></div></div>
	<div style="position: absolute; width: 280px; height: 130px;left: 50px; top: 30px; padding: 10px;" class="ui-widget ui-widget-content ui-corner-all">
		<div class="ui-dialog-content ui-widget-content" style="background: none; border: 0;">
			<p>오버래이 셰도우, 내용</p>
		</div>
	</div>
	-->
<!-- </div> -->

<!--
<h2 class="demoHeaders">아이콘 (content color preview)</h2>
<ul id="icons" class="ui-widget ui-helper-clearfix">
	<li class="ui-state-default ui-corner-all" title=".ui-icon-gripsmall-diagonal-se"><span class="ui-icon ui-icon-gripsmall-diagonal-se"></span></li>
	<li class="ui-state-default ui-corner-all" title=".ui-icon-grip-diagonal-se"><span class="ui-icon ui-icon-grip-diagonal-se"></span></li>
</ul>
-->

<!-- Datepicker
<h2 class="demoHeaders">데이트픽커</h2>
<div id="datepicker"></div>
 -->

<!-- Progressbar
<h2 class="demoHeaders">프로그레스바</h2>
<div id="progressbar"></div>
 -->

<!-- selectmenu
<h2 class="demoHeaders">셀렉트메뉴</h2>
<select id="selectmenu">
	<option>Slower</option>
	<option>Slow</option>
	<option selected="selected">Medium</option>
	<option>Fast</option>
	<option>Faster</option>
</select>
 -->

<!-- Spinner
<h2 class="demoHeaders">스피너</h2>
<input id="spinner">
 -->

<!-- Menu

 -->

<!-- Tooltip 
<h2 class="demoHeaders">툴팁</h2>
<p id="tooltip">
	<a href="#" title="That&apos;s what this widget is">Tooltips</a> can be attached to any element. When you hover
the element with your mouse, the title attribute is displayed in a little box next to the element, just like a native tooltip.
</p>
-->

<!-- Highlight / Error 
<h2 class="demoHeaders">하이라이트 / 에러</h2>
<div class="ui-widget">
	<div class="ui-state-highlight ui-corner-all" style="margin-top: 20px; padding: 0 .7em;">
		<p><span class="ui-icon ui-icon-info" style="float: left; margin-right: .3em;"></span>
		<strong>Hey!</strong> Sample ui-state-highlight style.</p>
	</div>
</div>
<br>
<div class="ui-widget">
	<div class="ui-state-error ui-corner-all" style="padding: 0 .7em;">
		<p><span class="ui-icon ui-icon-alert" style="float: left; margin-right: .3em;"></span>
		<strong>Alert:</strong> Sample ui-state-error style.</p>
	</div>
</div>
-->


<!--
<script src="common_libs/ui/external/jquery/jquery.js"></script>
<script src="common_libs/ui/jquery-ui.js"></script>
<script src="common_libs/ui/jquery-ui.custom.js"></script>
<script>


var availableTags = [
	"ActionScript",
	"AppleScript",
	"Asp",
	"BASIC",
	"C",
	"C++",
	"Clojure",
	"COBOL",
	"ColdFusion",
	"Erlang",
	"Fortran",
	"Groovy",
	"Haskell",
	"Java",
	"JavaScript",
	"Lisp",
	"Perl",
	"PHP",
	"Python",
	"Ruby",
	"Scala",
	"Scheme"
];
$( "#autocomplete" ).autocomplete({
	source: availableTags
});


$( "#button" ).button();

/*
$( "#progressbar" ).progressbar({
	value: 20
})
*/;
//$( "#spinner" ).spinner();

//$( "#tooltip" ).tooltip();
//$( "#selectmenu" ).selectmenu();

// Hover states on the static widgets
$( "#dialog-link, #icons li" ).hover(
	function() {
		$( this ).addClass( "ui-state-hover" );
	},
	function() {
		$( this ).removeClass( "ui-state-hover" );
	}
);

// Link to open the dialog
$( "#dialog-link" ).click(function( event ) {
	$( "#dialog" ).dialog( "open" );
	event.preventDefault();
});

$( "#datepicker" ).datepicker({
	inline: true
});



</script>


-->

	<div class="ui-dialog-content"><!-- 안쓰임 -->
		으아아아아
	</div>